version: '3.8'
services:
  api:
    container_name: menu-api
    restart: on-failure
    build: .
    environment:
      - MONGO_DB=menuapi
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URI_FORMAT=standard
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
  mongo:
    image: mongo:6.0.5
    container_name: menu-db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: